// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_TH_MT.Data;

#nullable disable

namespace QL_TH_MT.Migrations
{
    [DbContext(typeof(NewAppDbContext))]
    partial class NewAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QL_TH_MT.Models.DangKyLichThinhGiangNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaHoc")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int");

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<int>("SoTuanLienTiep")
                        .HasColumnType("int");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TuanBatDau")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("HopDongId");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("DangKyLichThinhGiangs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.HocKyNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BatDauHocKy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KetThucDangKyLich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KetThucHocKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KetThucNhapHopDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KetThucSapXepLich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KetThucThongBao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<int>("SoHocKy")
                        .HasColumnType("int");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TienHocKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("HocKys", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.HocPhanNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int");

                    b.Property<string>("MaHocPhan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nhom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SiSo")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MaHocPhan")
                        .IsUnique();

                    b.HasIndex("MonHocId");

                    b.ToTable("HocPhans", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.HopDongMonHocNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("HopDongId", "MonHocId")
                        .IsUnique();

                    b.ToTable("HopDongMonHocs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.HopDongNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("SoHopDong")
                        .IsUnique();

                    b.ToTable("HopDongs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.LichThucHanhNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuoiThu")
                        .HasColumnType("int");

                    b.Property<int>("CaHoc")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int");

                    b.Property<int>("HocPhanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDuyetTTDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThucHanh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetTTDTId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<int>("PhongThucHanhId")
                        .HasColumnType("int");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("TuanHoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("HocPhanId");

                    b.HasIndex("NguoiDuyetTTDTId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("PhongThucHanhId", "NgayThucHanh", "CaHoc")
                        .IsUnique();

                    b.ToTable("LichThucHanhs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.MonHocNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoBuoiThucHanh")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaMonHoc")
                        .IsUnique();

                    b.ToTable("MonHocs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhanMemNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DungLuong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhienBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhanMem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanMems", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhongThucHanhNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKiemKeGanNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiKiemKeId")
                        .HasColumnType("int");

                    b.Property<int>("SoMayHoatDong")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.HasIndex("NguoiKiemKeId");

                    b.ToTable("PhongThucHanhs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhongThucHanhPhanMemNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCaiDat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCaiDatId")
                        .HasColumnType("int");

                    b.Property<int>("PhanMemId")
                        .HasColumnType("int");

                    b.Property<int>("PhongThucHanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCaiDatId");

                    b.HasIndex("PhanMemId");

                    b.HasIndex("PhongThucHanhId");

                    b.ToTable("PhongThucHanhPhanMems", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.TaiKhoanNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoaiGiangVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@utc2.edu.vn",
                            HoTen = "Administrator",
                            MatKhauHash = "$2a$11$NmEjbxwRj9ZGjVOqoT/exOHnJjhV2IHbYleZeRq30cf1aeEW.ifN2",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            TrangThaiHoatDong = true,
                            VaiTro = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "pdt@utc2.edu.vn",
                            HoTen = "Phòng Đào Tạo",
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "pdt",
                            TrangThaiHoatDong = true,
                            VaiTro = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "ttdtth@utc2.edu.vn",
                            HoTen = "Trung tâm Đào tạo Thực hành",
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "ttdtth",
                            TrangThaiHoatDong = true,
                            VaiTro = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "tranphongnha@utc2.edu.vn",
                            HoTen = "Trần Phong Nhã",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "tranphongnha",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "tranthidung@utc2.edu.vn",
                            HoTen = "Trần Thị Dung",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "tranthidung",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 6,
                            Email = "phamthimien@utc2.edu.vn",
                            HoTen = "Phạm Thị Miên",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "phamthimien",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 7,
                            Email = "nguyenvuthai@utc2.edu.vn",
                            HoTen = "Nguyễn Vũ Thái",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "nguyenvuthai",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 8,
                            Email = "tranquockhanh@utc2.edu.vn",
                            HoTen = "Trần Quốc Khánh",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "tranquockhanh",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 9,
                            Email = "nguyenthienduong@utc2.edu.vn",
                            HoTen = "Nguyễn Thiện Dương",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "nguyenthienduong",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 10,
                            Email = "tranthiminhanh@utc2.edu.vn",
                            HoTen = "Trần Thị Minh Ánh",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "tranthiminhanh",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 11,
                            Email = "tranducanh@utc2.edu.vn",
                            HoTen = "Trần Đức Anh",
                            LoaiGiangVien = 2,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "tranducanh",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 12,
                            Email = "nguyendinhhien@utc2.edu.vn",
                            HoTen = "Nguyễn Đình Hiển",
                            LoaiGiangVien = 1,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "nguyendinhhien",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        },
                        new
                        {
                            Id = 13,
                            Email = "luutoandinh@utc2.edu.vn",
                            HoTen = "Lưu Toàn Định",
                            LoaiGiangVien = 1,
                            MatKhauHash = "$2a$11$2IJkqc0YrUUXkEplL8rjZOdNipz5MNcHJXrMhZHD47eYQKnnxLt5u",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "luutoandinh",
                            TrangThaiHoatDong = true,
                            VaiTro = 4
                        });
                });

            modelBuilder.Entity("QL_TH_MT.Models.ThongBaoNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LinkLienQuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiGuiId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiNhanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId", "DaDoc");

                    b.ToTable("ThongBaos", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.YeuCauDoiPhongNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaHocGoc")
                        .HasColumnType("int");

                    b.Property<int?>("CaHocMoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuPDT")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChuTTDT")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<bool?>("KetQuaDuyetPDT")
                        .HasColumnType("bit");

                    b.Property<bool?>("KetQuaDuyetTTDT")
                        .HasColumnType("bit");

                    b.Property<int>("LichThucHanhGocId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayDuyetPDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyetTTDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThucHanhGoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThucHanhMoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetPDTId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDuyetTTDTId")
                        .HasColumnType("int");

                    b.Property<int>("PhongGocId")
                        .HasColumnType("int");

                    b.Property<int?>("PhongMoiId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LichThucHanhGocId");

                    b.HasIndex("NguoiDuyetPDTId");

                    b.HasIndex("NguoiDuyetTTDTId");

                    b.HasIndex("PhongGocId");

                    b.HasIndex("PhongMoiId");

                    b.ToTable("YeuCauDoiPhongs", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.YeuCauMuonBuNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaHocMoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuPDT")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChuTTDT")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<bool?>("KetQuaDuyetPDT")
                        .HasColumnType("bit");

                    b.Property<bool?>("KetQuaDuyetTTDT")
                        .HasColumnType("bit");

                    b.Property<int>("LichThucHanhGocId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayDuyetPDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyetTTDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetPDTId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDuyetTTDTId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LichThucHanhGocId");

                    b.HasIndex("NguoiDuyetPDTId");

                    b.HasIndex("NguoiDuyetTTDTId");

                    b.ToTable("YeuCauMuonBus", (string)null);
                });

            modelBuilder.Entity("QL_TH_MT.Models.DangKyLichThinhGiangNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.HocKyNew", "HocKy")
                        .WithMany()
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.HopDongNew", "HopDong")
                        .WithMany("DangKyLichs")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("HopDong");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HocKyNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HocPhanNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.HocKyNew", "HocKy")
                        .WithMany()
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.MonHocNew", "MonHoc")
                        .WithMany("HocPhans")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HopDongMonHocNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.HopDongNew", "HopDong")
                        .WithMany("HopDongMonHocs")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.MonHocNew", "MonHoc")
                        .WithMany("HopDongMonHocs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HopDongNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.HocKyNew", "HocKy")
                        .WithMany("HopDongs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("QL_TH_MT.Models.LichThucHanhNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.HocKyNew", "HocKy")
                        .WithMany("LichThucHanhs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.HocPhanNew", "HocPhan")
                        .WithMany("LichThucHanhs")
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiDuyetTTDT")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetTTDTId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.PhongThucHanhNew", "PhongThucHanh")
                        .WithMany("LichThucHanhs")
                        .HasForeignKey("PhongThucHanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("HocPhan");

                    b.Navigation("NguoiDuyetTTDT");

                    b.Navigation("NguoiTao");

                    b.Navigation("PhongThucHanh");
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhongThucHanhNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiKiemKe")
                        .WithMany()
                        .HasForeignKey("NguoiKiemKeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiKiemKe");
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhongThucHanhPhanMemNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiCaiDat")
                        .WithMany()
                        .HasForeignKey("NguoiCaiDatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.PhanMemNew", "PhanMem")
                        .WithMany("PhongThucHanhs")
                        .HasForeignKey("PhanMemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.PhongThucHanhNew", "PhongThucHanh")
                        .WithMany("PhanMems")
                        .HasForeignKey("PhongThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCaiDat");

                    b.Navigation("PhanMem");

                    b.Navigation("PhongThucHanh");
                });

            modelBuilder.Entity("QL_TH_MT.Models.ThongBaoNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("QL_TH_MT.Models.YeuCauDoiPhongNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.LichThucHanhNew", "LichThucHanhGoc")
                        .WithMany()
                        .HasForeignKey("LichThucHanhGocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiDuyetPDT")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetPDTId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiDuyetTTDT")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetTTDTId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.PhongThucHanhNew", "PhongGoc")
                        .WithMany()
                        .HasForeignKey("PhongGocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.PhongThucHanhNew", "PhongMoi")
                        .WithMany()
                        .HasForeignKey("PhongMoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GiangVien");

                    b.Navigation("LichThucHanhGoc");

                    b.Navigation("NguoiDuyetPDT");

                    b.Navigation("NguoiDuyetTTDT");

                    b.Navigation("PhongGoc");

                    b.Navigation("PhongMoi");
                });

            modelBuilder.Entity("QL_TH_MT.Models.YeuCauMuonBuNew", b =>
                {
                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.LichThucHanhNew", "LichThucHanhGoc")
                        .WithMany()
                        .HasForeignKey("LichThucHanhGocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiDuyetPDT")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetPDTId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QL_TH_MT.Models.TaiKhoanNew", "NguoiDuyetTTDT")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetTTDTId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GiangVien");

                    b.Navigation("LichThucHanhGoc");

                    b.Navigation("NguoiDuyetPDT");

                    b.Navigation("NguoiDuyetTTDT");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HocKyNew", b =>
                {
                    b.Navigation("HopDongs");

                    b.Navigation("LichThucHanhs");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HocPhanNew", b =>
                {
                    b.Navigation("LichThucHanhs");
                });

            modelBuilder.Entity("QL_TH_MT.Models.HopDongNew", b =>
                {
                    b.Navigation("DangKyLichs");

                    b.Navigation("HopDongMonHocs");
                });

            modelBuilder.Entity("QL_TH_MT.Models.MonHocNew", b =>
                {
                    b.Navigation("HocPhans");

                    b.Navigation("HopDongMonHocs");
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhanMemNew", b =>
                {
                    b.Navigation("PhongThucHanhs");
                });

            modelBuilder.Entity("QL_TH_MT.Models.PhongThucHanhNew", b =>
                {
                    b.Navigation("LichThucHanhs");

                    b.Navigation("PhanMems");
                });
#pragma warning restore 612, 618
        }
    }
}
